# Generated by Django 6.0.1 on 2026-02-02 12:13
# Update existing roles with detailed permissions from centralized configuration

from django.db import migrations


def update_role_permissions(apps, schema_editor):
    """Update all roles with permissions from centralized config"""
    Role = apps.get_model('users', 'Role')
    from core.constants import get_all_roles_config
    
    roles_config = get_all_roles_config()
    
    for role_name, config in roles_config.items():
        try:
            role = Role.objects.get(name=role_name)
            role.permissions = config['permissions']
            role.description = config['description']  # Update description too
            role.save()
        except Role.DoesNotExist:
            # Create if doesn't exist (shouldn't happen, but safe)
            Role.objects.create(
                name=config['name'],
                description=config['description'],
                permissions=config['permissions']
            )


def reverse_permissions(apps, schema_editor):
    """Reverse migration - clear all permissions"""
    Role = apps.get_model('users', 'Role')
    Role.objects.all().update(permissions={})


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_default_roles"),
    ]

    operations = [
        migrations.RunPython(update_role_permissions, reverse_permissions),
    ]
