# Generated by Django 6.0.1 on 2026-02-02 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique course code (e.g., CS101, MATH201)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Course name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly slug (auto-generated)",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed course description"
                    ),
                ),
                (
                    "credits",
                    models.PositiveIntegerField(
                        default=3, help_text="Number of credit hours"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "is_elective",
                    models.BooleanField(
                        default=False, help_text="Whether this is an elective course"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this course is currently active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic level (NULL for general courses)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="academics.level",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        help_text="Semester (NULL for general courses)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses_course",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CoursePrerequisite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Whether this prerequisite is mandatory"
                    ),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True,
                        help_text="Minimum required grade (e.g., C+, B)",
                        max_length=5,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course that has prerequisites",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="courses.course",
                    ),
                ),
                (
                    "prerequisite",
                    models.ForeignKey(
                        help_text="The required prerequisite course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_courses",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Prerequisite",
                "verbose_name_plural": "Course Prerequisites",
                "db_table": "courses_prerequisite",
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["level", "semester"], name="courses_cou_level_i_64dc73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_active", "status"], name="courses_cou_is_acti_73629a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprerequisite",
            index=models.Index(
                fields=["course"], name="courses_pre_course__54695a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprerequisite",
            index=models.Index(
                fields=["prerequisite"], name="courses_pre_prerequ_598637_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseprerequisite",
            unique_together={("course", "prerequisite")},
        ),
    ]
