# Generated by Django 6.0.1 on 2026-02-02 13:38

from django.db import migrations


def create_default_levels_and_semesters(apps, schema_editor):
    """
    Create default levels and semesters from centralized configuration.
    Follows DRY principle - single source of truth in core.constants.
    """
    Level = apps.get_model('academics', 'Level')
    Semester = apps.get_model('academics', 'Semester')
    
    # Import configuration from centralized constants
    from core.constants import get_all_levels_config, get_all_semesters_config
    
    # Create default levels
    levels_config = get_all_levels_config()
    for code, config in levels_config.items():
        Level.objects.get_or_create(
            code=config['code'],
            defaults={
                'name': config['name'],
                'description': config['description'],
                'order': config['order'],
                'is_active': config['is_active'],
            }
        )
    
    # Create default semesters
    semesters_config = get_all_semesters_config()
    for code, config in semesters_config.items():
        Semester.objects.get_or_create(
            code=config['code'],
            defaults={
                'name': config['name'],
                'description': config['description'],
                'order': config['order'],
                'duration_weeks': config['duration_weeks'],
                'is_active': config['is_active'],
            }
        )


def reverse_default_data(apps, schema_editor):
    """Remove default levels and semesters"""
    Level = apps.get_model('academics', 'Level')
    Semester = apps.get_model('academics', 'Semester')
    
    Level.objects.all().delete()
    Semester.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_levels_and_semesters,
            reverse_default_data
        ),
    ]
